### ISSUE TITLE
Syntax error of delete statement on MySQL 5.7

### ISSUE THREAD

**Issue by taretmch** [zio/zio-protoquill#159]
When I execute this delete query on MysqlJdbcContext (MySQL 5.7):

```scala
ctx.run(quote {
  query[TestTable].filter(_.id == 1).delete
})
```

a following syntax error occurs:

```
[error] java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS x3 WHERE x3.id = 1' at line 1
[error]         at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[error]         at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[error]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[error]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[error]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[error]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1350)
[error]         at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[error]         at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[error]         at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction$$anonfun$1(JdbcContextVerbExecute.scala:40)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.withConnectionWrapped$$anonfun$1$$anonfun$1(JdbcContextVerbExecute.scala:33)
[error]         at io.getquill.context.jdbc.JdbcContext.wrap(JdbcContext.scala:54)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.withConnectionWrapped$$anonfun$1(JdbcContextVerbExecute.scala:33)
[error]         at io.getquill.context.jdbc.JdbcContext.withConnection$$anonfun$1(JdbcContext.scala:63)
[error]         at scala.Option.getOrElse(Option.scala:201)
[error]         at io.getquill.context.jdbc.JdbcContext.withConnection(JdbcContext.scala:65)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.withConnectionWrapped(JdbcContextVerbExecute.scala:33)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.withConnectionWrapped$(JdbcContextVerbExecute.scala:13)
[error]         at io.getquill.context.jdbc.JdbcContext.withConnectionWrapped(JdbcContext.scala:16)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction(JdbcContextVerbExecute.scala:40)
[error]         at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction$(JdbcContextVerbExecute.scala:13)
[error]         at io.getquill.context.jdbc.JdbcContext.executeAction(JdbcContext.scala:16)
[error]         at Sample$.$anonfun$3(Sample.scala:43)
[error]         at Sample$.delete(Sample.scala:43)
[error]         at delete.main(Sample.scala:37)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
```

This error means that if we declare an alias for a table, we must use the alias when referring to the table:

```
DELETE t1 FROM test AS t1, test2 WHERE ...
```

The generated query by ProtoQuill has a syntax error:

```
DELETE FROM test_table AS x3 WHERE x3.id = 1
```

Ref: https://dev.mysql.com/doc/refman/5.7/en/delete.html

**Version**: `4.0.0`
**Module**: `quill-jdbc`
**Database**: `mysql 5.7`

### Expected behavior

Delete query doesn't have syntax errors. Generated query must be:

```
DELETE x3 FROM test_table AS x3 WHERE x3.id = 1
```

### Actual behavior

Delete query has syntax errors. Generated query is:

```
DELETE FROM test_table AS x3 WHERE x3.id = 1
```

### Steps to reproduce the behavior

This issue cannot be reproduced using mirror contexts.

On MySQL 5.7, a table definition is

```sql
mysql> CREATE TABLE test_table(
  id bigint(20) unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

mysql> desc test_table;
+-------+---------------------+------+-----+---------+----------------+
| Field | Type                | Null | Key | Default | Extra          |
+-------+---------------------+------+-----+---------+----------------+
| id    | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| name  | varchar(32)         | NO   |     | NULL    |                |
+-------+---------------------+------+-----+---------+----------------+
```

and the reproduce code is:

```scala
@main def delete =
  import io.getquill._
  val ctx = new MysqlJdbcContext(SnakeCase, "sample.context")
  case class TestTable(id: Long, name: String)
  import ctx._

  ctx.run(quote {
    query[TestTable].filter(_.id == 1).delete
  })
```

GitHub:
- https://github.com/taretmch/protoquill-sandbox/blob/db8d4a0c650c04b680550575c68e8a496265bc81/src/main/scala/IssueReproduceSample.scala
- https://github.com/taretmch/protoquill-sandbox/blob/db8d4a0c650c04b680550575c68e8a496265bc81/database/init/db.sql#L19-L22

### Workaround

I cannot find workarounds.

@getquill/maintainers

**Comment by mem-memov** [comment]
For Scala 2 version there was recently a fix https://github.com/zio/zio-quill/issues/2545. Suffering from this issue in my Scala 3 project.

**Comment by deusaquilus** [comment]
Should be fixed in 4.3.0. @mem-memov could you please try?

**Comment by mem-memov** [comment]
Thank you very much for this fix. I'll apply it tomorrow and report here the results.

**Comment by mem-memov** [comment]
I've checked version 4.3.0. It still produces aliases in DELETE statements at compile time.
Sorry, don't know how to load 4.3.0-SNAPSHOT as Maven dependency

```
<dependency>
    <groupId>io.getquill</groupId>
    <artifactId>quill-jdbc-zio_3</artifactId>
    <version>4.3.0-SNAPSHOT</version>
</dependency>
```
It produces an error: Could not find artifact io.getquill:quill-jdbc-zio_3:pom:4.3.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots)

Same error with 4.4.0-SNAPSHOT

**Comment by olmeras** [comment]
Same occurs on 4.3.1-SNAPSHOT:
`query[Token].filter(_.id(lift(token.id))).delete`

Produces:
`DELETE FROM token x3 WHERE x3.id = 1;`

Instead of:
`DELETE x3 FROM token x3 WHERE x3.id = 1;`

**Comment by liranco4** [comment]
The same occurs on 4.6.0

**Comment by renjiandreamore** [comment]
my compile time query is: DELETE FROM my_table x8 WHERE x8.id = 123, instead, it should be no alias... my quill version is 4.6.0

**Comment by dispalt** [comment]
If you override the MySQLDialect and set

```
  override def useActionTableAliasAs: SqlIdiom.ActionTableAliasBehavior = SqlIdiom.ActionTableAliasBehavior.Hide
```

I think it produces a more correct result for mysql.

**Comment by renjiandreamore** [comment]
@dispalt really appreciate the info here, it works!

**Comment by mahe-ymc** [comment]
Hm, my delete queries still come with Aliases, despite using `SqlIdiom.ActionTableAliasBehavior.Hide`. @renjiandreamore does this really work for you?

**Comment by mahe-ymc** [comment]
Ah, sorry, I'm using Scala 2 version.

**Comment by guizmaii** [comment]
Can someone try with `v4.7.3`, please? We merge the support of Mysql5 dialect in `v4.7.0`

**Comment by dispalt** [comment]
> @guizmaii
> 
> I still get table alias and fails in AWS Aurora MySQL
> 
> val zioVersion = "2.0.13" val quillVersion = "4.8.0" or "4.7.3" scalaVersion := "3.3.1"
> 
> Quill Query (compiled in 7ms): DELETE FROM sla x2 WHERE x2.sla_id = ? [info] 41 | quote { [info] 42 | slaQuote.filter(_.sla_id == lift(id)).delete [info] 43 | } [info] 44 | }

Are you using the new dialect?

**Comment by jimmyaug** [comment]
@guizmaii 
I am using a similar pattern to what is mentioned in here https://zio.dev/ecosystem/templates and present here
https://github.com/ScalaConsultants/zio-scala3-quickstart.g8

I am not sure I can choose the dialect here because I am relying on **io.getquill.jdbczio.Quill.MySql**

Layer defined as

```scala
  private val mysqlLayer = Quill.Mysql.fromNamingStrategy(Literal)
  ```
repo

```scala
object SlaRepositoryLive:

  val layer: URLayer[Quill.Mysql[Literal], SlaRepository] = ZLayer {
    for {

      quill <- ZIO.service[Quill.Mysql[Literal]]
    } yield SlaRepositoryLive(quill)
  }
  ```
 Quill.MySql uses **MySQLDialect**

```scala 
   class Mysql[+N <: NamingStrategy](val naming: N, override val ds: DataSource)
    extends Quill[MySQLDialect, N] with MysqlJdbcTypes[MySQLDialect, N] {
    val idiom: MySQLDialect = MySQLDialect
    val dsDelegate = new MysqlZioJdbcContext[N](naming)
  }
  object Mysql {
    def apply[N <: NamingStrategy](naming: N, ds: DataSource) = new Mysql[N](naming, ds)
    def fromNamingStrategy[N <: NamingStrategy: Tag](naming: N): ZLayer[javax.sql.DataSource, Nothing, Mysql[N]] =
      ZLayer.fromFunction((ds: javax.sql.DataSource) => new Mysql[N](naming, ds))
  }
  ```

**Comment by theqp** [comment]
I have overrode `idiom` in `MySql` with the following code but I still get the same error
```scala
object DbContext {
  val live: URLayer[DataSource, Quill.Mysql[SnakeCase]] =
    ZLayer.fromFunction((ds: DataSource) =>
      new Quill.Mysql(SnakeCase, ds) {
        // workaround for https://github.com/zio/zio-protoquill/issues/159
        override val idiom: MySQLDialect = MySQL5Dialect
      }
    )
}
```

```
Exception in thread "zio-fiber-80" java.sql.SQLSyntaxErrorException: (conn=38) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'a WHERE a.foo_id IN (1)' at line 1
```

looks like there is still an alias but without `AS`
